name: comal
description: Desktop and Mobile Audio Book Player.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^6.0.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: ^5.0.2
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8

dev_dependencies:
  auto_route_generator: ^6.0.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
